# Taps

tap "anomalyco/tap"
tap "charmbracelet/tap"
tap "dcchambers/tap"
tap "googlecontainertools/kpt"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "manaflow-ai/cmux"
tap "tarkah/tickrs"
tap "teamookla/speedtest"
tap "tinygo-org/tools"

# Brew Formula

brew "age"
brew "achannarasappa/tap/ticker"
brew "anomalyco/tap/opencode"
brew "asciinema"
brew "atuin"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "bat-extras"
brew "chrome-cli"
brew "crystal"
brew "dcchambers/tap/notekeeper"
brew "eza"
brew "fastfetch"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "fx"                        # TUI Json viewer
brew "gifski"                    # Gif encoder
brew "gist"
brew "git"
brew "git-delta"                 # Better git diff output
brew "git-who"
brew "gh"                        # https://cli.github.com/
brew "gnu-sed"
brew "go"
brew "gojq"
brew "goto"
brew "gpg"
brew "httpie"
brew "jaq"                       # jq with extra features
brew "jqp"
brew "lazydocker"
brew "lazygit"
brew "libyaml"                   # ruby-build dependency
brew "lnav"                      # log viewing tool - https://lnav.org/
brew "m-cli"
brew "mas"
brew "mise"
brew "neovim"
brew "numbat"
brew "nushell"
brew "onefetch"
brew "pandoc"
brew "pass"                      # https://www.passwordstore.org/
brew "python"                    # TODO - Use mise instead to manage python install
brew "ripgrep"
brew "rga"                       # https://github.com/phiresky/ripgrep-all
brew "ruby-build"
brew "rustup-init"
brew "scc"                       # like cloc
brew "shellcheck"
brew "silicon"
brew "slides"
brew "sqlite"
brew "sttr"
brew "tarkah/tickrs/tickrs"
brew "teamookla/speedtest/speedtest"
brew "tinygo-org/tools/tinygo"
brew "tlrc"                      # tldr in Rust
brew "tree"
brew "tty-clock"
brew "watchman"
brew "yt-dlp"
brew "yq"
brew "zoxide"                    # See also: https://github.com/rupa/z

# Casks (Graphical Apps)

## Calendar
cask "itsycal"

## Utilities & Productivity
cask "1password"
cask "1password-cli"
cask "anki"                          # https://apps.ankiweb.net/
cask "basictex"
cask "espanso"                       # https://espanso.org/
cask "handy"                         # https://handy.computer/
cask "jordanbaird-ice"               # https://icemenubar.app/
cask "maestral"                      # https://maestral.app/ - Dropbox Client
cask "ollama"                        # https://ollama.com/
cask "raycast"
cask "rectangle"
cask "setapp"                        # See setapp.txt
cask "silicon-app"
cask "shortcat"
cask "tailscale-app"
cask "ticktick"                      # https://ticktick.com/
cask "tomatobar"
cask "trex"

## Markdown, Notes, & PKM
cask "mark-text"
cask "notion"
cask "obsidian"

## Media & News
cask "iina"                          # https://iina.io/
cask "netnewswire"
cask "vlc"                           # https://www.videolan.org/vlc/

## Software Engineering
cask "db-browser-for-sqlite"
cask "ghostty"
cask "gitify"                        # https://gitify.io/
cask "httpie"
cask "manaflow-ai/cmux/cmux"
cask "orbstack"                      # https://orbstack.dev/
cask "postgres-unofficial"           # https://postgresapp.com/
cask "rapidapi"
cask "visual-studio-code"
cask "zed"
cask "zed@preview"

## Fonts
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspace-nerd-font"

##  Messaging
cask "discord"
cask "hey-desktop"
cask "whatsapp"

## Web
cask "firefox"
cask "google-chrome"
cask "orion"

## Gaming
cask "steam"
cask "steamcmd"

# Cargo Crates (Rust package manager)

cargo "htmlq"
cargo "difftastic"

## Python Packages

uv "json-schema-for-humans"
