# Taps
tap "abhimanyu003/sttr"
tap "charmbracelet/tap"
tap "cooklang/tap"
tap "cue-lang/tap"
tap "dcchambers/tap"
tap "eth-p/software"
tap "googlecontainertools/kpt"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homeport/tap"
tap "noahgorstein/tap"
tap "tarkah/tickrs"
tap "teamookla/speedtest"
tap "tinygo-org/tools"
tap "vmware-tanzu/carvel"

# Brew Formula (CLI tools)
brew "act"
brew "age"
brew "achannarasappa/tap/ticker"
brew "asciinema"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "borgbackup"
brew "borgmatic"
brew "charmbracelet/tap/skate"
brew "chrome-cli"
brew "cooklang/tap/cook"
brew "crane" # https://github.com/google/go-containerregistry/blob/main/cmd/crane/README.md
brew "crystal"
brew "cue-lang/tap/cue"
brew "dark-mode"
brew "darksky-weather"
brew "dcchambers/tap/cbonsai"
brew "dcchambers/tap/kubeval"
brew "dcchambers/tap/writeas-cli"
brew "dhall-json"
brew "dog"
brew "duf"
brew "eth-p/software/bat-extras"
brew "eza"
brew "ffmpeg"
brew "ffsend"
brew "fish"
brew "fzf"
brew "fx"
brew "gifski"
brew "gist"
brew "git"
brew "git-delta"
brew "gh"
brew "glow"
brew "gnu-sed"
brew "go"
brew "golangci-lint"
brew "go-jsonnet"
brew "gojq"
brew "googler"
brew "goto"
brew "gpg"
brew "gron"
brew "helix"
brew "helm"
brew "heroku/brew/heroku"
brew "hexyl"
brew "homeport/tap/dyff"
brew "httpie"
brew "jaq"
brew "jless"
brew "joplin-cli"
brew "jq"
brew "jql"
brew "k9s"
brew "kapp" # vmware-tanzu/carvel/kapp
brew "kpt" # googlecontainertools/kpt/kpt
brew "kubectx"
brew "kubernetes-cli" #Minikube dependency, but useful to list still
brew "kubie"
brew "kustomize"
brew "krew"
brew "lastpass-cli"
brew "lazydocker"
brew "lazygit"
brew "libyaml" # needed for rbenv/ruby-build
brew "lnav"
brew "lynx"
brew "m-cli"
brew "mas"
brew "micro"
brew "minikube"
brew "mise"
brew "mkcert"
brew "most"
brew "neofetch"
brew "neovim"
brew "newsboat"
brew "nmap"
brew "nnn"
brew "noahgorstein/tap/jqp"
brew "node"
brew "notekeeper"
brew "numbat"
brew "nushell"
brew "onefetch"
brew "pandoc"
brew "pass"
brew "plantuml"
brew "podman"
brew "prettyping"
brew "python"
brew "ranger"
brew "ripgrep"
brew "rizin"
brew "rga"
brew "ruby-build"
brew "rustup-init"
brew "scc"
brew "shellcheck"
brew "silicon"
brew "slides"
brew "speedtest" # Official Ookla speedtest
brew "speedtest-cli" # From github.com/sivel/speedtest-cli
brew "sqlite"
brew "sshuttle"
brew "sttr"
brew "tarkah/tickrs/tickrs"
brew "task"
brew "tealdeer" # tldr.sh rust implementation
brew "terminal-notifier"
brew "tinygo-org/tools/tinygo"
brew "tmux"
brew "timewarrior"
brew "transmission-cli"
brew "tree"
brew "tty-clock"
brew "vim"
brew "vendir"
brew "watchman"
brew "watson"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "yt-dlp"
brew "yq"
brew "zellij"
brew "zoxide" # See also: https://github.com/rupa/z

# Casks (Graphical .app programs)

## Audio
cask "eqmac"
cask "soundsource"

## Books/E-Readers
cask "calibre"
cask "remarkable"

## Calendar
cask "itsycal"

## MacOS Productivity
cask "1password"
cask "1password-cli"
cask "command-x"
cask "raycast"
cask "rectangle"
cask "silicon-app"
cask "shortcat"
cask "trex"

## Markdown, Notes & PKM
cask "heynote"
cask "mark-text"
cask "notion"
cask "obsidian"
cask "typora"

## Media
cask "iina"
cask "netnewswire"
cask "transmission"
cask "vlc"

## Programming
### APIs
cask "httpie"
cask "rapidapi"

### Containers/Kubernetes
cask "docker"

### Database
cask "db-browser-for-sqlite"
cask "postgres-unofficial" # https://postgresapp.com/

### Fonts
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspace-nerd-font"

### Hex Editors/Reverse Engineering
cask "cutter"
cask "imhex"
# See also: rizin, hexyl

### IDEs/Text Editors
cask "visual-studio-code"
cask "zed"
cask "zed@preview"

### Terminal
cask "ghostty"

##  Messaging
cask "discord"
cask "hey-desktop"
cask "whatsapp"

##  Misc
cask "gitify"
cask "jordanbaird-ice"

## Productivity
cask "ticktick"

## Screen Recording
cask "cap"           # https://cap.so/
cask "kap"           # https://getkap.co/
cask "obs"           # https://obsproject.com/
cask "screen-studio" # https://screen.studio/ - Requires license.

## Web
cask "firefox"
cask "google-chrome"
cask "orion"

## To-be categorized
cask "anki"
cask "basictex"
cask "inkscape"
cask "ollama" # Provides a GUI app to install/manage the ollama cli
cask "krita"
cask "maestral" # dropbox client
cask "setapp" # See setapp.txt
cask "steam"
cask "steamcmd"
cask "tailscale"
cask "tomatobar"
