live_config_reload = true

#theme
import = [
    "~/Code/personal/alacritty-theme/themes/solarized_light.toml"
]

#font
[font]
size = 16

[font.bold]
family = "MonaspiceAr Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonaspiceAr Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonaspiceAr Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspiceAr Nerd Font"
style = "Regular"
